version: "3.8"
services:
  app:
    build:
      context: ./docker/php-fpm
      args:
        - DOCKER_PHP_VERSION=${PHP_VERSION}
    volumes:
      - ./backend:/work

  web:
    build:
      context: ./docker/nginx
      args:
        - DOCKER_NGINX_VERSION=${NGINX_VERSION}
    ports:
      - 10080:80
    volumes:
      - ./backend:/work/backend

  db:
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      TZ: UTC
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/pgsql-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/data:/data

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025