version: "3.8"
services:
  php-fpm:
    build:
      context: ./docker/php-fpm
      args:
        - DOCKER_PHP_VERSION=${PHP_VERSION}
    volumes:
      - ./backend:/work

  nginx:
    build:
      context: ./docker/nginx
      args:
        - DOCKER_NGINX_VERSION=${NGINX_VERSION}
    ports:
      - 10080:80
    volumes:
      - ./backend:/work/backend

  postgres:
    build:
      context: ./docker/postgres
      args:
        - DOCKER_POSTGRES_VERSION=${POSTGRES_VERSION}
        - DOCKER_POSTGRES_DATABASE=${POSTGRES_DATABASE}
        - DOCKER_POSTGRES_USER=${POSTGRES_USER}
        - DOCKER_POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/pgsql-data:/var/lib/postgresql/data

  redis:
    build:
      context: ./docker/redis
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis/data:/data

  mailhog:
    build: ./docker/mailhog
    ports:
      - 1025:1025
      - 8025:8025