version: "3.8"
services:
  app:
    build:
      context: ./docker/php
      args:
        - DOCKER_PHP_VERSION=${PHP_VERSION}
    volumes:
      - ./backend:/work

  web:
    build:
      context: ./docker/nginx
      args:
        - DOCKER_NGINX_VERSION=${NGINX_VERSION}
    ports:
      - 10080:80
    volumes:
      - ./backend:/work/backend